source 'http://rubygems.org'

gem 'sinatra'
gem 'dropbox', '>= 1.2.0'
gem 'activerecord'
gem 'rack'
gem 'sqlite3-ruby', '>= 1.3.1'
gem 'less'
gem 'memcached'
#gem 'manifesto-pierot', :git => 'git://github.com/pierot/manifesto-pierot.git'