source 'http://rubygems.org'

gem 'sinatra'
gem 'dropbox', '>= 1.2.2'
gem 'activerecord'
gem 'database_cleaner'
gem 'rack'
gem 'sqlite3-ruby', '>= 1.3.1'
gem 'pony'
gem 'passenger'
gem 'rake'
# gem 'manifesto-pierot', '>= 0.6.2', :git => 'git://github.com/pierot/manifesto-pierot.git'
